### ISSUE TITLE
The server is undergoing maintenance/Error Code 13212

### ISSUE THREAD

**Issue by keiichimaebaras** [kuroppoi/entralinked#10]
Hello! I made a Github account just for this, and I don't know a lot about servers, so apologies if I seem naive. I am attempting to tuck in a Pokemon with Entralinked on White 2 with my regular Nintendo DS (as my N2DS didn't seem to work). However, even though (I assume?) the server is running on my Surface with the .jar file, the game spits out an error that says the server is under maintenance. Is there a way to fix this? It reaches the Game Sync screen with the purple background, but then says the error.

**Comment by kuroppoi** [comment]
For future reference; Entralinked never sends this error, so if this happens to you then you’ve probably incorrectly configured the DNS settings of your DS.

**Comment by minuro63** [comment]
Hi, I somehow get Error 13212 on specific aspects of Entralinked when I am changing C-Gear Skins/Pokedex Skins/Pokemon Musical music. Everything else on Entralinked works and updates fine on both the server and the cartridge sides. Would it be possible that there's an undiscovered issue with Error 13212? The error appeared in both v.1.3.2 and v.1.3.4.

I am running a Korean Pokemon Black 2 cartridge on a New 3DS, and I attach my log file here [latest.log](https://github.com/kuroppoi/entralinked/files/12327758/latest.log). Thank you very much for your time!

**Comment by kuroppoi** [comment]
> Hi, I somehow get Error 13212 on specific aspects of Entralinked when I am changing C-Gear Skins/Pokedex Skins/Pokemon Musical music. Everything else on Entralinked works and updates fine on both the server and the cartridge sides. Would it be possible that there's an undiscovered issue with Error 13212? The error appeared in both v.1.3.2 and v.1.3.4.
> 
> I am running a Korean Pokemon Black 2 cartridge on a New 3DS, and I attach my log file here [latest.log](https://github.com/kuroppoi/entralinked/files/12327758/latest.log). Thank you very much for your time!

See my previous message. Make sure you have no other connections configured on your 3DS.
