### ISSUE TITLE
Finding Primary DNS code for Entralinked

### ISSUE THREAD

**Issue by Reqii** [kuroppoi/entralinked#12]
Where exactly does entralinked tell you the primary DNS you're supposed to enter in the 3DS internet settings? I have been stuck on error 13212 for quite some time.

**Comment by kuroppoi** [comment]
If Entralinked started without any issues, the DNS will be displayed below the output log in the user interface next to the "Open User Dashboard" button.

**Comment by Reqii** [comment]
Sorry for seeming naive, but I don't see a "Open User Dashboard" button after executing "entralinked.jar".

**Comment by kuroppoi** [comment]
It probably didn't execute correctly, then.
Make sure that `jar` files are associated with the correct Java executable.

**Comment by Reqii** [comment]
I believe it*s the correct java executable due to the fact that "entralinked.jar" has the Java logo before executing it, but not sure. Also is the aforementioned jar file meant to executed by pressing "Open in associated application" or is double clicking it the correct method.

**Comment by kuroppoi** [comment]
Double clicking should work, but sometimes it just uses the wrong executable for some reason.
You can try using [jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) and see if that resolves the issue.

**Comment by Reqii** [comment]
I've already tried using jarfix, I don't see a difference.

**Comment by kuroppoi** [comment]
What happens exactly when executing Entralinked?

**Comment by Reqii** [comment]
I'm directed to several folders/files (most which I think require extracting to open) after a popup of it executing. Should I send a picture of what I see after having executed the .jar file?

**Comment by kuroppoi** [comment]
Sure, maybe that'll help clarify things.

**Comment by Reqii** [comment]
![Screenshot (2)](https://github.com/kuroppoi/entralinked/assets/140891145/e817720c-5cc7-4aad-a984-3dfd895d0732)
A picture

**Comment by kuroppoi** [comment]
It's opening the file as a ZIP archive, which obviously isn't supposed to happen.
Try right clicking -> "Open with" and manually select the right java executable.
Alternatively, you could run `java -jar entralinked.jar` in a command prompt.

**Comment by Reqii** [comment]
Alright, so when trying the first solution I get the "A Java exception has occured" and the command prompt is unable to find the jarfile when running the code you just sent.

**Comment by kuroppoi** [comment]
"A Java exception has occured" often suggests that your Java version is outdated. You have to use Java 17 or newer.
Command prompt has to be run in the same directory as where `entralinked.jar` is located.

**Comment by Reqii** [comment]
I use Java 17 and could you elaborate on "Command prompt has to be run in the same directory as where entralinked.jar is located."

**Comment by kuroppoi** [comment]
Do you have multiple Java installations? Make sure you're executing Entralinked using the correct one.

**Comment by Reqii** [comment]
The only other Java installation I have is JRE-1.8. Perhaps it's causing conflicts with Java 17?

**Comment by kuroppoi** [comment]
Doubt it, but when using "Open with" you need to make sure to use the Java executable from your Java 17 installation.

**Comment by Reqii** [comment]
When I try that the window opens briefly and shuts down automatically.

**Comment by kuroppoi** [comment]
Run using `javaw.exe` instead of `java.exe`

**Comment by Reqii** [comment]
Nothing happens when I try that.

**Comment by kuroppoi** [comment]
Well that's odd. Maybe just try uninstalling and reinstalling Java.

**Comment by Reqii** [comment]
I did try with JDK 20 and the same thing occurs.

**Comment by kuroppoi** [comment]
Well, try opening a command prompt in the folder where `entralinked.jar` is and run the command `java -jar entralinked.jar`

**Comment by Reqii** [comment]
Alright, I've managed to get to the screen where entralinked tells me which DNS server I'm supposed to configurate my DS for but now I can't connect to WFC.

**Comment by kuroppoi** [comment]
What error code do you get?

**Comment by Reqii** [comment]
20100

**Comment by kuroppoi** [comment]
SSL might not be working properly. Check the output log and make sure there aren’t any errors.

**Comment by Reqii** [comment]
Unsure about SSL, I'm not getting any errors to my knowledge but I am finding a few errors that could potenially be preventing me from creating a Game Sync.

**Comment by kuroppoi** [comment]
Best just post the entire log in here

**Comment by Reqii** [comment]
![Screenshot (2)](https://github.com/kuroppoi/entralinked/assets/140891145/26e328f5-e39a-455f-bda4-95e2cd7ad298)
![Screenshot](https://github.com/kuroppoi/entralinked/assets/140891145/64b99f5c-4ab9-4962-ac7f-3e1916966031)

**Comment by kuroppoi** [comment]
Thought so. Entralinked has no read/write permissions wherever you are running it. Try moving it to a location where it is allowed to create files and see if it’ll start without any errors then.
Alternatively, you could run it from a command prompt ran as administrator.

**Comment by Reqii** [comment]
Where would I move Entralinked?

**Comment by kuroppoi** [comment]
Anywhere other than where it is now. Maybe your desktop.

**Comment by Reqii** [comment]
That is not possible.

**Comment by kuroppoi** [comment]
How so?

**Comment by Reqii** [comment]
Don't have one.

**Comment by kuroppoi** [comment]
Every PC should have one

**Comment by Reqii** [comment]
Sorry, misunderstood what you said for a moment but I don't see any errors when opening after moving it

**Comment by kuroppoi** [comment]
Well, try using Game Sync now

**Comment by Reqii** [comment]
Should the secondary DNS be the same as the primary?

**Comment by kuroppoi** [comment]
Doesn’t matter

**Comment by Reqii** [comment]
Now I'm getting both error code 60000 and 52210 (I've already tried erasing and reconfigurating).

**Comment by kuroppoi** [comment]
What kind of DS system are you using?

**Comment by Reqii** [comment]
3DS

**Comment by kuroppoi** [comment]
Do you have a generation 4 game by any chance?

**Comment by Reqii** [comment]
Yes

**Comment by kuroppoi** [comment]
To erase WFC configuration on 3DS, start that game and on the main menu where you can select Mystery Gift etc. choose an option called “Nintendo WFC Settings” (or anything similar to it) then “Options” and “Erase Nintendo WFC Configuration”.

**Comment by Reqii** [comment]
Why not from the the 3DS system settings?

**Comment by kuroppoi** [comment]
Because it won't let you erase it from there, idk why ask Nintendo

**Comment by Reqii** [comment]
If I'm using a hotspot to connect to Nintendo WFC does the PC also have to be connected to the hotspot for Entralinked to work?

**Comment by kuroppoi** [comment]
Yes

**Comment by Reqii** [comment]
Just confirming but the IP-address is meant to be Auto-obtained, correct?

**Comment by kuroppoi** [comment]
That's correct in most cases

**Comment by Reqii** [comment]
I've now managed to create a Game Sync ID, but I'm forced to wait 24h before trying to tuck in a pokemon. Is there anyway to bypass this?

**Comment by kuroppoi** [comment]
This sometimes just happens for some reason, no idea why. Unfortunately all you can do now is wait until the timer expires.

**Comment by Reqii** [comment]
I've managed to tuck in a Pokemon into Game Sync.

**Comment by Reqii** [comment]
Hey, sorry for reopening the issue, the question is unrelated to the title and everything else but how do I change the c-gear skin and make sure that the Pokemon I choose on the dashboard appear in Entralink?

**Comment by Reqii** [comment]
Got it. Thank you for all the help.
