### ISSUE TITLE
Can't connect to WFC across different Generation 5

### ISSUE THREAD

**Issue by Reqii** [kuroppoi/entralinked#13]
Can't connect to WFC via the Primary DNS-setting provided by Entralinked in BW while it works without any problems on B2W2. Is there a specific reason for this?

**Comment by kuroppoi** [comment]
I need more information. Do you get any errors?

**Comment by Reqii** [comment]
I get error code 60000 (I've erased and reconfigurated internet settings several times) and 522210 respectively.

**Comment by kuroppoi** [comment]
You probably incorrectly erased the settings, as we had previously talked about in [#12](https://github.com/kuroppoi/entralinked/issues/12#issuecomment-1657109728).

**Comment by kuroppoi** [comment]
[Release v1.3.3](https://github.com/kuroppoi/entralinked/releases/tag/v1.3.3) adds a tool that allows you to easily fix this issue.
