### ISSUE TITLE
Error code 052110-1

### ISSUE THREAD

**Issue by Snantx** [kuroppoi/entralinked#14]
Wont connect to internet after using the DNS from the app, using DSI if that matters

**Comment by kuroppoi** [comment]
There's a multitude of possible causes for this error. Here are some you can check for:
- The DNS is not configured correctly.
- Entralinked is not displaying the correct DNS. Make sure that it matches the private IPv4 of your PC.
- Your DS is not connected to the same network as your PC.
- A firewall is blocking communcations between Entralinked and your DS. Make sure that your firewall allows Java to communicate.
- Other software (such as a VPN or Virtual Machine) might be causing interference.
