### ISSUE TITLE
Using Entralinked to spawn in items like Reveal Glass?

### ISSUE THREAD

**Issue by bbysung** [kuroppoi/entralinked#18]
hi, i found this willy nilly (i watched a guy called johnstone presumably use it, i dont think he confirmed that he did i just saw this in a comment) and with B2 being my favorite childhood game, i figured why not give it a shot. 

i follow all the directions, and to my surprise it actually works. and what's amazing about it is that i have absolutely no idea *how* it's even possible, but i saw it with my own eyes so i have no choice ¹but to believe it. i put my mewtwo to sleep, check the site and find out hes in the computer apparently--- press options, wake him up, and everything i selected showed up _in the game_. on my actual 3ds and real copy of black 2. which is fking mind blowing to me, but that's besides the point.

i'm asking this to avoid corrupting my save file or anything; it it possible to spawn in key/event items, like the reveal glass, using entralinked? the option is technically there, but i still wanna ask if it works just to be safe.

**Comment by kuroppoi** [comment]
It doesn't pose a risk as far as I know, but I haven't done any in-depth testing so I can't give a completely satisfactory answer.
I'd advise against using it to obtain story-related key items as it might mess with event flags later on (again; not sure about this, could be wrong) but key items such as the Reveal Glass or Gracidea _should_ be fine.

As for straight up save file corruptions, I haven't had anything like that happen during all my testing so the chances of that occurring are slim to none.

**Comment by bbysung** [comment]
okay!! thank you so much!! also one last question--- can this work with a DSi?

**Comment by kuroppoi** [comment]
Yes

**Comment by bbysung** [comment]
i spawned in both the reveal glass and the gracidea, no other key items, and i can confirm that they were received with no problem..... buuuuut they don't actually serve their purpose since the shaymin & carnation trio aren't actual event mons... which is unfortunate, but i can at least have shaymin sky/land seperatly & the genies arent exactly my favorites anyway

**Comment by kuroppoi** [comment]
Oh yeah, the Gracidea only works on Fateful Encounter Shaymin and it seems that the Reveal Glass has some checks in place to make sure it wasn't just cheated into the game. That is unfortunate.
