### ISSUE TITLE
How does the recharging cooldown for Game Sync work?

### ISSUE THREAD

**Issue by bbysung** [kuroppoi/entralinked#20]
hi again, ever since i got it to work yesterday ive been waiting for the "Game Sync has run out of energy. It will take one day to recharge it. Please wait for one day without changing the DS system you're using, and then use Game Sync again" message to disappear.

it's definitely been 24 hours since i got it to work that first time, so i've been trying to log in... and failing every time. 

for context the timeline of events looks something like this:
- tucks pokemon in at roughly 3:40 PM
- wakes it up approximately 20 minutes later
- fast forward, i'm swapping between two seperate DS systems at roughly 11 PM. i unfortunately do not have an exact time that i put the cartridge back in the same DS i got it to work on, but i haven't taken it out again since.
- cue me getting the above error repeatedly at various times throughout the day (it's 11:30 PM now)

so i suppose i'm asking: is there any way to know/find out how the cooldown works? i'm definitely connected because there's no error code; i'm more confused/curious about how the cooldown works so i can work around it

**Comment by kuroppoi** [comment]
Swapping DS systems or changing the time while on cooldown will reset the timer, so it’s best to wait 24 hours without doing either of those things.

**Comment by bbysung** [comment]
i got it turns out i do in fact just have to be patient 👍 thanks anyway!
