### ISSUE TITLE
Gen5 Pokemon are missing

### ISSUE THREAD

**Issue by MegaKBang** [kuroppoi/entralinked#21]
Everything is working perfectly now! I can't believe I finally get to experience Gamesync!
When I tried to add a few of the version exclusive mons, I noticed that the entire Gen5 Dex is missing in the dropdown menu.
So Pokemon like Throh or the Gen5 Starters are currently impossible to get via your tool.

Also, do you have a Paypal or something for donations? I don't have any coding experience, but want to support it least with a donation.

**Comment by kuroppoi** [comment]
Glad to hear everything is working!
Unfortunately, Generation 5 Pokémon cannot appear in Entree forest in Black & White, and can thus not be downloaded through Game Sync.
They are available in Black 2 & White 2, but only a handful of them.

And thank you for the kind gesture but I'm not accepting donations at the moment :)

**Comment by zurgeg** [comment]
> Glad to hear everything is working! Unfortunately, Generation 5 Pokémon cannot appear in Entree forest in Black & White, and can thus not be downloaded through Game Sync. They are available in Black 2 & White 2, but only a handful of them.
> 
> And thank you for the kind gesture but I'm not accepting donations at the moment :)

BTW, they are available in B/W (non-2) afaik, Zekrom/Reshiram I know for a fact, and I think Victini also could be obtained

**Comment by kuroppoi** [comment]
> > Glad to hear everything is working! Unfortunately, Generation 5 Pokémon cannot appear in Entree forest in Black & White, and can thus not be downloaded through Game Sync. They are available in Black 2 & White 2, but only a handful of them.
> > And thank you for the kind gesture but I'm not accepting donations at the moment :)
> 
> BTW, they are available in B/W (non-2) afaik, Zekrom/Reshiram I know for a fact, and I think Victini also could be obtained

I tested every dex number on both games and unfortunately only a few could be downloaded through Game Sync in B2W2 only.
