### ISSUE TITLE
Error 60000 once (Profile unknown), then error 52200 all after (Connection test failed) while connecting Italian Black 2.

### ISSUE THREAD

**Issue by SSUPII** [kuroppoi/entralinked#23]
No new string is printed in the server log. Made sure to disable AP Isolation and WiFi Segregation in the router settings for the guest network the Nintendo DS is connecting to.

The Nintendo DS can be pinged from the host machine while it attempts to connect.

DNS settings of the console where both first and second DNS address to the machine Entralinked is hosted on.

Server is running on Debian Linux 12 Bookworm x86_64, OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)

**Comment by kuroppoi** [comment]
Connection test failure doesn't really matter in a lot of cases.
For fixing error 60000, please follow the [troubleshooting guide.](https://github.com/kuroppoi/entralinked/wiki/Troubleshooting#60000-followed-by-52200)

**Comment by SSUPII** [comment]
I can confirm manually setting Friend Code and Nintendo Wi-Fi Connection ID in the server software worked.

Unfortunately, I cannot test further as the game was saved in a difference console (emulator) before trying this on real hardware.

--

By the way, this was done on a Nintendo 3DS and the troubleshooting page doesn't mention it. If you want, I can add the mention there. An important thing of note is that on 3DS you cannot delete the Nintendo Wi-Fi data from Nintendo DS mode, you must do it from normal mode.
