### ISSUE TITLE
hi, It's not really a problem, but rather a doubt

### ISSUE THREAD

**Issue by Briosh1812** [kuroppoi/entralinked#25]
I don't know how to see my wifi connection ID, could you help me?

**Comment by liketolike** [comment]
![image](https://github.com/kuroppoi/entralinked/assets/88918365/40616ff0-ac26-4788-8a9c-eff26cc5cf08)

**Comment by Briosh1812** [comment]
Thank you very much, I don't know English very well, and that complicated me a little, but thank you very much

**Comment by Briosh1812** [comment]
![image](https://github.com/kuroppoi/entralinked/assets/147357287/374acfa0-48da-43dc-b4d5-3ad9e6613e50)


I really don't understand why it shows this, I went to system information, saw my Nintendo WFC ID, put it in, and it shows that it doesn't exist.
