### ISSUE TITLE
Game Sync cooldown not working

### ISSUE THREAD

**Issue by Waso2** [kuroppoi/entralinked#26]
After doing every step for the first time, I got my game sync id, but instead of letting me sleep a pokemon, it said that it need one day to recharge. I read the other closed question about recharge, but is not the same question, since he managed to make it work at least once before the cooldown, which is not my case. I waited anyway 24 hours plus some minutes to be sure, and after it connects, I got the same message. I didn’t change the time, the console, or the connection, so the timer doesn’t reset. I dont know what can be the problem.

**Comment by kuroppoi** [comment]
Try again tomorrow

**Comment by zurgeg** [comment]
> Try again tomorrow

@kuroppoi You probably already know, but it seems that the GS recharge error also happens if the state of the server and game is desynced (i.e., game thinks no pokemon is sleeping, but server disagrees, or vice versa). No clue why though

**Comment by kuroppoi** [comment]
> > Try again tomorrow
> 
> @kuroppoi You probably already know, but it seems that the GS recharge error also happens if the state of the server and game is desynced (i.e., game thinks no pokemon is sleeping, but server disagrees, or vice versa). No clue why though

I never really looked into it but it might be what the weird check at `0x021B74D2` is.
In any case, the cooldown should expire on its own eventually.
