### ISSUE TITLE
Issues with DNS server

### ISSUE THREAD

**Issue by greatestnotgamer** [kuroppoi/entralinked#29]
Using issues closed beforehand, I was able to get the server to almost work. However, I have an issue when starting a DNS server on an Arch-Linux based machine. Here I have the log pasted from the terminal.
[logdream.txt](https://github.com/kuroppoi/entralinked/files/13246106/logdream.txt)

**Comment by kuroppoi** [comment]
Another process is already using port 53, you’ll have to kill that process.

**Comment by greatestnotgamer** [comment]
TCP or UDP?

**Comment by kuroppoi** [comment]
UDP, I'm not sure how you'd go about finding it on linux, sorry.

**Comment by Agvantibo** [comment]
> TCP or UDP? and how do I find/kill that process?

`sudo netstat -lnp | grep ':53'`
