### ISSUE TITLE
One or more servers failed to start

### ISSUE THREAD

**Issue by CatWhiskersMan** [kuroppoi/entralinked#3]
I've been attempting to run entralinked.jar in Linux and both the GUI and non-GUI forms output an error saying that one or more servers failed to start. I've attached my log to paint a clearer picture of the problem I'm facing:

[latest.log](https://github.com/kuroppoi/entralinked/files/11894091/latest.log)

**Comment by kuroppoi** [comment]
It seems you're using a Unix-based system. Ports `53`, `80` and `443` are privileged ports that can only be operated by root.
Have you tried running the application using `sudo`?

**Comment by CatWhiskersMan** [comment]
Hi I've been able to run the application using sudo and it seems to resolve the issue, however the application still will not start. I have attached my latest log. 

[latest.log](https://github.com/kuroppoi/entralinked/files/11910837/latest.log)

**Comment by kuroppoi** [comment]
> Hi I've been able to run the application using sudo and it seems to resolve the issue, however the application still will not start. I have attached my latest log.
> 
> [latest.log](https://github.com/kuroppoi/entralinked/files/11910837/latest.log)

The server itself started without any problems, which is good!
Seems it just can't create the GUI for some reason.
If it doesn't bother you then you can just ignore it and proceed to use the program.
