### ISSUE TITLE
Persistent 20100 Error

### ISSUE THREAD

**Issue by DoctorDisease** [kuroppoi/entralinked#31]
Have followed the quick start guide to the letter, as well as the posted solution for this error code, yet it still persists.

**Comment by kuroppoi** [comment]
Please attach the program log file

**Comment by DoctorDisease** [comment]
[2023-11-15-1.log](https://github.com/kuroppoi/entralinked/files/13366639/2023-11-15-1.log)
[2023-11-15-2.log](https://github.com/kuroppoi/entralinked/files/13366640/2023-11-15-2.log)
[2023-11-15-3.log](https://github.com/kuroppoi/entralinked/files/13366644/2023-11-15-3.log)
[latest.log](https://github.com/kuroppoi/entralinked/files/13366647/latest.log)
This is all 4 Log files I have. The issue has now degenerated and I cannot even successfully connect my 3ds to the internet when the DNS is entered.

**Comment by kuroppoi** [comment]
Double-check your DNS settings and delete your other access point configurations if you have any.
Make sure that your connection is stable, and keep an eye out for any changes in the error message.

**Comment by DoctorDisease** [comment]
Will do when able, I'll get back to you then. Thank you very much for starting this project in the first place, let alone still being active on it.

**Comment by DoctorDisease** [comment]
Alright I've finally had time to sit down. My DNS was correct, I deleted my other saved connection setting and I am now encountering a communication error with no code. It reads "Communication error... Disconnecting from Nintendo WiFi Connection." which only appears onscreen for about 2 seconds before flashing to "Communication error..." I did encounter this issue several times beforehand and neglected to mention that earlier.

**Comment by kuroppoi** [comment]
Peculiar.
When does the error appear exactly? Immediately after the Musharna screen ends, or does it hang on the tuck-in screen for a good while?
Might be worth checking out #19

**Comment by DoctorDisease** [comment]
This error appears after the Musharna screen but before I have the option to tuck a Pokemon in if it will help I can record a video really quick

**Comment by kuroppoi** [comment]
A video would be helpful, if it's not a hassle :)

**Comment by DoctorDisease** [comment]
Here you are, it is incredibly similar to the video already posted in #19 
https://youtu.be/HQF_wPnioDo?si=jofK8uo0Q-hZkrGT
And the log from the connection attempt in the video 
[latest.log](https://github.com/kuroppoi/entralinked/files/13369294/latest.log)

**Comment by kuroppoi** [comment]
I don't know why this happens, but switching to another network solved the problem for the other person.

**Comment by DoctorDisease** [comment]
Unfortunately that did not work for me, the network I switched to was a mobile hotspot and the error in the video persisted.

**Comment by kuroppoi** [comment]
I'm gonna look into it

**Comment by DoctorDisease** [comment]
I have managed to obtain a game sync ID by switching to my Japanese cartridge on an Original NDS model, as well as using the hotspot. I am now at the stage of waiting 1 day to use the service, Is there anyway to skip that?

**Comment by kuroppoi** [comment]
I don't know of a way to bypass the cooldown, sorry

**Comment by ashgx** [comment]
I remember that you can get around this restriction by modifying the time to reach it, for example, today, November 16th, and then modifying it to be after November 17th

> I have managed to obtain a game sync ID by switching to my Japanese cartridge on an Original NDS model, as well as using the hotspot. I am now at the stage of waiting 1 day to use the service, Is there anyway to skip that?

I remember that you can get around this restriction by modifying the time to reach it, for example, today, November 16th, and then modifying it to be after November 17th

**Comment by kuroppoi** [comment]
Sorry for taking a while, I've just pushed [release v1.3.5](https://github.com/kuroppoi/entralinked/releases/tag/v1.3.5) which adds a few lines of debug logging.

If you could try to reproduce the issue on the new version then hopefully the new debug log file located at `logs/debug.log` will provide more insight as to where exactly it goes wrong.
