### ISSUE TITLE
Error code 52212 and "This Wi-Fi Connection ID does not exist."

### ISSUE THREAD

**Issue by Camwoodstock** [kuroppoi/entralinked#33]
When trying to connect to Game Sync, the game spits out this error code--both from the main menu and in-game. Trying to follow both the protocol for 052110-x or 60000 are dead ends;

- In the former's case, I cannot locate _anything_ Java-related in the firewall; neither an inclusion nor an exclusion. Perhaps I didn't look hard enough because I was tired? Admittedly, I'm not used to searching the firewall, but no key words such as "Java", "Adoptium", or "Temurin" were present.
- In the latter's case, I tried to follow the protocol for 60000, despite getting 52212 to start with and not seeing any 60000 code. After grabbing the Pal Pad code and Wifi CID, it bafflingly declared the Wi-Fi CID didn't exist and didn't clarify further. I double-checked, there was not a typo in there, so I have zero clue what that's about.

Admittedly, I've got no clue what is going on here. My only guess is an obscure firewall setting, but it's unclear just what I need to do there (at least, to my tired brain, it is 2:12 AM as I write this).

**Comment by kuroppoi** [comment]
I don't think I've ever seen that one before.
Try searching the firewall for programs containing `OpenJDK` or some such as well.

In the meantime, please provide program logs so I can see if perhaps it goes wrong at a specific step:

1. Use the newest version if you aren't already (1.3.6 as of this message)
2. Start the program and try using Game Sync
3. After failing to connect and getting the error code screen, send the log file located at `logs/debug.log` here

**Comment by Camwoodstock** [comment]
That is well and truly baffling. Connected to the Poke Classic Network, and then on opening the game, it immediately yells _**OY WHAT'RE YOU DOING YOUR WIFI DATA MAY HAVE JUST BEEN ERASED!!!**_

...my friendcode is entirely unchanged, no clue what that was about.

**Comment by kuroppoi** [comment]
> That is well and truly baffling. Connected to the Poke Classic Network, and then on opening the game, it immediately yells _**OY WHAT'RE YOU DOING YOUR WIFI DATA MAY HAVE JUST BEEN ERASED!!!**_
> 
> ...my friendcode is entirely unchanged, no clue what that was about.

Did you switch to another DS perhaps? If not, it probably doesn't mean anything... probably

**Comment by kuroppoi** [comment]
If you got that message then it is at least successfully connecting to the Game Sync server, which means that everything should be working correctly.
As for the cooldown -- it just seems to happen sometimes when the game detects that you've recently changed the time or played on another system. The best thing to do is to not do either of those things while you wait for the cooldown to expire.
I'll close the issue as resolved, but feel free to comment here if you have any other problems or questions regarding this issue.

Also, I take it that some sort of antivirus was causing the problem? Would be helpful to know for future reference, in case anyone else runs into similar problems :)

**Comment by Camwoodstock** [comment]
The antivirus in specific was VIPRE, but I'd wager just about any antivirus with a firewall option that acts independently of Windows' in-house one can also decide to act a fool. The fix was fortunately simple; it was port 80 from "javaw.exe", so whitelist that executable.
