### ISSUE TITLE
Persistent error 13212

### ISSUE THREAD

**Issue by Vegito2121** [kuroppoi/entralinked#35]
I'm on a N3DSXL and setup a connection in the DS wifi settings after deleting the existing ones and set only the primary DNS to the right one and still get the error

**Comment by kuroppoi** [comment]
Where are you configuring DNS settings? Entralinked does not send this error code ever.

**Comment by Vegito2121** [comment]
> Where are you configuring DNS settings? Entralinked does not send this error code ever.

In the DS wifi settings

**Comment by kuroppoi** [comment]
Which ones specifically? The 3DS has two menus where you can configure internet connections.
You have to configure one in the 3DS internet settings.

**Comment by Vegito2121** [comment]
At first I only did the DS settings and when that didn't work I also did the same in the 3DS settings

**Comment by Vegito2121** [comment]
Not sure if it's relevant info but I also have 2 other connections setup in the 3DS wifi settings

**Comment by kuroppoi** [comment]
You have to delete those 2 other connections.

**Comment by Vegito2121** [comment]
Okay

**Comment by Vegito2121** [comment]
That fixed it 👍
