### ISSUE TITLE
[issue?] Update PID not working for me?

### ISSUE THREAD

**Issue by k7at6** [kuroppoi/entralinked#37]
I wanted to mess around a bit with the dream world for a bit and I was able to troubleshoot the program as much as I could. I'm currently using the latest release and I was able to have the wifi connect to my 3ds but was given Error 60000. But in trying to change the PID to get the program working, I was given an error with the invalid friend code even though I was inputting my regular friend code. 
Am I formatting my friendcode incorrectly or is this actually an issue? I've been formatting it like XXXX-XXXX-XXXX or XXXXXXXXXXXX.

**Comment by kuroppoi** [comment]
Both formats will work. Are you sure that the friend code you’re entering is correct?
