### ISSUE TITLE
Error code 23500

### ISSUE THREAD

**Issue by Antonio231102** [kuroppoi/entralinked#4]
At first glance, the server seems to start normally, however, upon trying to connect from melonDS, I receive error code 23500. The server also reports some issues on [the log](https://github.com/kuroppoi/entralinked/files/11903551/latest.log).

**Comment by kuroppoi** [comment]
Well that’s funny, it seems like the device birth date is in hex format?
For now, set the birthday month of your device to an early month such as January and try again.
