### ISSUE TITLE
Nintendo Network ID Problem

### ISSUE THREAD

**Issue by Preflext** [kuroppoi/entralinked#40]
my fault i dont know how to remove this but i figured out what i need to do, sorry for the inconveinice and bad spelling

**Comment by Preflext** [comment]
i thought i knew what i was doing because i saw something that had seemed like it would fix my problem and i thought i messed up by asking for a solution to this issue. 

i cannot get entralinked to give me the dns i have to input into my 3ds and it seems that it stops working at trying to get to the http server and i had not realized, so i went to "help" than "update pid" and tried inputting my details but it had stated that my NID did not exist. i am not currently running an antivirus, vpn, or virtual machine on my device. i am on mac os currently and here is my current log: 
[latest copy.log](https://github.com/kuroppoi/entralinked/files/13995926/latest.copy.log)
to be fair i also do not know what i am doing, i am just trying to follow the quick setup guide

**Comment by kuroppoi** [comment]
Did it work before? For some reason it has no permission to bind to certain ports. What OS are you running this on?
Might be similar to issue #3.

**Comment by Preflext** [comment]
my mac version is 10.13.6💀. it is an old macbook pro that was given to me because my other laptop broke when i was going to do this before. if running it in sudo may work how do i do that because to be honest with you im brain dead when it comes to commands sometimes. now that im looking at it, it may just be that my thing is severely old but i want to make sure i try everything

**Comment by kuroppoi** [comment]
Presumably `sudo java -jar path/to/entralinked.jar`
