### ISSUE TITLE
Add the ability to get mystery gifts using the same server

### ISSUE THREAD

**Issue by ScarlettHaze** [kuroppoi/entralinked#42]
Makes it easier plus people can use their own custom mystery gifts without having to use dwc network server emulator which can be very tedious to setup.

**Comment by kuroppoi** [comment]
It's an interesting idea, but it's beyond the scope of this project and it would involve reworking the entire DLS1 server.

**Comment by kuroppoi** [comment]
It can now distribute Mystery Gifts to both DPPtHGSS & BW/B2W2.
