### ISSUE TITLE
change dns /port

### ISSUE THREAD

**Issue by NewJoker1999** [kuroppoi/entralinked#43]
"By default, Entralinked is configured to automatically use the local host of the system.
This approach is not always accurate, however, and you may need to manually configure it in config.json."

I'm trying to create a Nintendo "hub", is there a way to change the port and/or DNS on which the application works? how?

**Comment by NewJoker1999** [comment]
> You can change the value of `hostName` in `config.json` and the DNS server will use that instead. The port cannot be changed because there's not much of a point since the DS wouldn't be able to connect if you changed it.

I was asking because maybe I'm ignorant, I set the 2 IPs from the PC settings, one for this and one for (forgive the spam) DNS-server which acts as a DNS hub, but even if you use 2 different IPs, it still gives me an error

**Comment by NewJoker1999** [comment]
> > You can change the value of `hostName` in `config.json` and the DNS server will use that instead. The port cannot be changed because there's not much of a point since the DS wouldn't be able to connect if you changed it.
> 
> I was asking because maybe I'm ignorant, I set the 2 IPs from the PC settings, one for this and one for (forgive the spam) DNS-server which acts as a DNS hub, but even if you use 2 different IPs, it still gives me an error

that is, logically I think that since they are different IPs, even if the port is the same it shouldn't cause problems, but it does

**Comment by kuroppoi** [comment]
What kind of error are you getting, and what are you trying to do?

**Comment by NewJoker1999** [comment]
I'm trying to start two "DNS servers" on the same PC, one for the sync link of Pokemon and the other for the WFC servers, but even if they have different IPs it tells me that the port is already in use

**Comment by kuroppoi** [comment]
`hostName` only changes what the DNS server points to, not what IP the program actually binds to.
