### ISSUE TITLE
Request for Pokemon Games Gen 6 & 7 Global Link (Game Sync) Emulator

### ISSUE THREAD

**Issue by Priestyle** [kuroppoi/entralinked#44]
Hey sorry for my last message which was about ignoring this request. I changed my mind once again and I want to see if this request could be fulfilled. My request was if you could emulate a generation 6 and 7 games Pokemon Global Link Game Sync server. Please let me know if you could do this!

**Comment by kuroppoi** [comment]
Did it have any cool features? I don't think I ever really played around with it myself.

**Comment by Priestyle** [comment]
It didn't have any cool features like changing pokedex skins but could you do it anyways just cause lmao - Oh actually there is one cool feature like being able to sync photos that you took in XY

**Comment by MaxAkito** [comment]
A big one is that medals in XY were entirely reliant on game sync, game sync checked your save data and awarded you medals based on flags, this functionality didn't last long, but restoring it would add back an essentially lost feature of X and Y.

**Comment by Priestyle** [comment]
Hey it's been 5 months. Kuroppoi, I have a question, is this even possible? Without official files from Nintendo? Assuming the recreation is like a dummy, sort of like Entralinked.

**Comment by kuroppoi** [comment]
I'd say it's possible but would probably not be as interesting as a standalone thing since it would require a modded console because (to my knowledge) no SSL bug has been found for the 3DS yet.

**Comment by Priestyle** [comment]
Hey, this is just a new idea but could you develop a standalone homebrew app that connects to Pretendo that has the Global Link features of gen 6 and 7 games that uses the Game Sync feature in the game?

**Comment by kuroppoi** [comment]
Probably not. I'm personally not too interested, especially if it has to rely on console modding to work.
