### ISSUE TITLE
Request for Battle Competition Downloadable Online Records / Digital Player ID

### ISSUE THREAD

**Issue by Priestyle** [kuroppoi/entralinked#45]
Hey I want to make a request that's just for aesthetics and for completedness. Can we can have downloadable digital player ID cards or online records for battle competition like in the picture below?

![2024-03-03-19-21-00-chrome-rPw1Wx7RAU](https://github.com/kuroppoi/entralinked/assets/52426313/9d872ea8-c691-4732-8c23-567f688b5a7b)

**Comment by kuroppoi** [comment]
From what I've gathered this would require setting up another server endpoint which might not be worth the trouble, especially since random matchup isn't functional anyway.
