### ISSUE TITLE
Running Entralinked on a Remote/ Cloud Server

### ISSUE THREAD

**Issue by KFenole** [kuroppoi/entralinked#52]
Was wondering if anyone had tried running Entralinked outside their local network, or if such a configuration would be possible. I've skimmed the source code but am not very experienced with Java and networking is not my expertise.

My goal is to run Entralinked from Heroku so that I can access it wherever I am. Would this work, and if not what kinds of modifications would be needed? Thanks

**Comment by kuroppoi** [comment]
In theory it should work fine, but since it's not local you'll have to make sure that `hostName` in `config.json` is properly configured.
