### ISSUE TITLE
Game Freezes/Never Loads When Entering Entree forest

### ISSUE THREAD

**Issue by Nicholas456** [kuroppoi/entralinked#54]
I used entralinked to add 10 dittos to the forest, and gave myself 20 rare candies. After waking up my pokemon I went into the forest and the game would either freeze or never load Any idea why this may have occured or how to fix it?

**Comment by kuroppoi** [comment]
That is not normal. Have you messed with a save editor in the past? It might be worth inspecting your save file.

**Comment by Nicholas456** [comment]
I have looked at the save in PkHex but it does not let me see the data fro what's currently in the Entree Forest. Other than that I have not looked into any save editors

**Comment by kuroppoi** [comment]
Exporting the save file with PKHeX might fix the save file if there are any problems with it, but I'm not entirely sure.
In any case, I don't think simply using Game Sync can cause this problem. Are you playing on cartridge? Try using your save on an emulator and see if the crash happens there as well. Could be a hardware issue.

**Comment by Nicholas456** [comment]
I am playing on cartridge, and unfortunately exporting from PKHeX didn't seem to fix the issue. I ran the save file on an emulator and went into the forest successfully, but what I saw made absouletly no sense
![Screenshot (59)](https://github.com/kuroppoi/entralinked/assets/49210095/e09921c3-ba05-4cde-b948-7feafcd4bf25)

**Comment by kuroppoi** [comment]
Looks like your Entree Forest is filled with garbage. I don't know what could cause this aside from save editing or cheating.
What happens if you try to start an encounter?

**Comment by Nicholas456** [comment]
When I talk to any of these NPCs the game just crashes. As for save editing/cheating, the only changes I made via PKHeX was to add mystery gift cards to my game. I used Entralinked in between adding those and didn't encounter this issue so I am not certain if that is the cause. Do you know of a way to clear the garbage from Entree Forest?

**Comment by Nicholas456** [comment]
Using that tool alongside an older save with a clean forest I was able to inject a clean forest into the corrupt save and when I entered the forest the forest was empty. I don't know if this will work on my cartridge, but I will give it a try
