### ISSUE TITLE
Difficulties connecting to gamesync

### ISSUE THREAD

**Issue by Yuhboyyy** [kuroppoi/entralinked#55]
I know this is just a basic issue that I thought troubleshooting would help, but I genuinely cant get it to work. Any time i try to connect to gamesync using entralinked it won't. I have double checked the primary dns. When I use the secondary as 0.0.0.0, it gives the basic "cant connect to network" and when i use 8.8.8.8 it says that the wfc service is shut down. I have made sure that the file can read and write, ive tried mobile hotspot as well as home wi-fi, i made sure i only have 1 wi-fi connection configured on my 2ds, made sure both my pc and ds were on the same network, etc. I would really like to get the game sync medal so help would be much appreciated. Thank you in advanced!

**Comment by kuroppoi** [comment]
What error code does it give you when you connect with the **secondary** DNS set to `0.0.0.0`?
