### ISSUE TITLE
Random Matchup

### ISSUE THREAD

**Issue by Priestyle** [kuroppoi/entralinked#56]
Can you implement random matchup? I'm very frustrated when I want to play random matchup but it's not implemented yet.

**Comment by kuroppoi** [comment]
Random Matchup isn't related to Game Sync, so I'm not sure why you're asking here.
Anyway, it cannot be implemented because there is currently no way to generate valid signatures, which the game requires in order to start the battle.
See: mm201/pkmn-classic-framework#116
