### ISSUE TITLE
Memory link is not working

### ISSUE THREAD

**Issue by DittoLink** [kuroppoi/entralinked#58]
Every time i input Pokemon Black's GameSync ID in Pokemon Black2,game screen always prompt communicate error.

![1](https://github.com/kuroppoi/entralinked/assets/43905487/e6571e0d-b2e6-4146-a8f6-ea2f1f4f580c)

**Comment by kuroppoi** [comment]
Can you provide the `logs/debug.log` file?

**Comment by DittoLink** [comment]
> Can you provide the `logs/debug.log` file?

[debug.log](https://github.com/kuroppoi/entralinked/files/15287670/debug.log)

**Comment by kuroppoi** [comment]
Nothing seems out of the ordinary there, and I can't reproduce the issue.
Does it always happen no matter how many times you try?

**Comment by DittoLink** [comment]
> Nothing seems out of the ordinary there, and I can't reproduce the issue. Does it always happen no matter how many times you try?

I figured out that the problem caused by VirtualBox's virtual Host-Only Ethernet Adapter.

I've succeeded test memory link function on Windows 8.
