### ISSUE TITLE
Loblloly's Studio

### ISSUE THREAD

**Issue by Priestyle** [kuroppoi/entralinked#6]
When I talk to Loblloly in Nacrene City after Game Syncing, she doesn't give you the options to switch the furnitures. I've tested this on entralinked 1.0.0 and 1.1.0.

**Comment by kuroppoi** [comment]
Did a bit of research, I assume this is what you mean?
As far as I know these only had a use in the Dream World, but it might be interesting to look into it anyway for the sake of completeness.
![image](https://github.com/kuroppoi/entralinked/assets/68156848/442e20eb-0313-4d08-8756-00d4509f5300)

**Comment by kuroppoi** [comment]
Feature has been implemented as of v1.2.0.
I say "implemented", but you can't really *do* anything with it. Still, it's pretty neat I'd say.

**Comment by Priestyle** [comment]
I just wanted to add that the decor options change every day/every time you do a game sync so could you change it so that the dummy decors do rotations or something?

**Comment by kuroppoi** [comment]
It’s possible, I’m just not sure what the point would be.
