### ISSUE TITLE
Error code: 54010

### ISSUE THREAD

**Issue by Kingboozx3** [kuroppoi/entralinked#63]
Whenever I try to deposit a Pokémon, it gives me this error code, but I can still see it on my Game Sync profile. But when I try to take it out, it tells me to deposit a Pokémon. My PC box still shows the Pokémon in it but for some reason, so it is in the dream world at the same time. Idk if this is because I used a different cartridge than I did the first few times, but I have a feeling that is not the issue.

**Comment by kuroppoi** [comment]
Typically the result of a weak internet connection.
