### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by Zeno97** [kuroppoi/entralinked#64]
I've runned it and works everything.
I saw it can be runned without the gui and just uses ports 80, 443, 53 and 90900
Technically speaking, is possible to run it in a VPS disabling the gui? If I change DNS of my DS with public ip the program should work too, or not?
I've read the thread on the repository of pkmnclassic framework. I would like to understand why it has not progressed in main repository if here it is basically all done. Maybe there is not enough interest from people in this project? Or there is some difficult I am not understanding?

PS: I am a software engineer and I work mostly with php but also I do mobile applicatons in java and for this I understand most of your code.

**Comment by kuroppoi** [comment]
Yes, it should work fine when hosting it on a VPS or somesuch, though the PID tool for bypassing error 60000 cannot be accessed remotely which might be inconvenient.
Implementing it in pkmn-classic would probably involve a bit more than just a barebones Game Sync emulator with a simple dashboard for selecting content and is something that will have to be discussed in greater detail.
