### ISSUE TITLE
Error 13203: data directory already exists

### ISSUE THREAD

**Issue by saltysodapop** [kuroppoi/entralinked#67]
Hi there, I’m currently unable to use game sync at all due to Error 13203 (can't register player the because data directory already exists). I’m aware that another user already created (and closed) an issue for this error a few months ago, however since no solution was discussed I hope it’s okay for me to create another issue for the same error. 

Like the previous user, I had been able to successfully use Entralinked multiple times before. At first I tried waiting a few days to see if the problem would fix itself, then I tried a number of possible solutions on my end (restarting my computer, using a different connection, etc.), but none of them worked. Here’s what the log says whenever I try to use game sync:

2024-08-04 00:14:39.428  INFO : Created GameSpy session for user 2322-XXXX-XXXX-XXXX
2024-08-04 00:14:39.569  INFO : User 2322-XXXX-XXXX-XXXX logged in with profile 602472462
2024-08-04 00:14:39.768  INFO : Created PGL session for user 2322-XXXX-XXXX-XXXX
2024-08-04 00:14:45.260  WARN : Can't register player QAAU8TEY2E because the data directory already exists!
2024-08-04 00:14:53.511  INFO : User 2322-XXXX-XXXX-XXXX logged out of profile 602472462

Additionally, whenever I open Entralinked, the log states that there was an error due to a FileNotFoundException, but the program just continues without loading any player(s). 

Any help with this would be very much appreciated!!

**Comment by kuroppoi** [comment]
Did you tamper with any of the player data? Try deleting the `players/QAAU8TEY2E` folder.

**Comment by saltysodapop** [comment]
As far as I'm aware, I haven't tampered with the player data at all (I didn't even know where to find it until I encountered this error), so I'm not sure what initially caused the error. Luckily, this solution appears to have fixed it; thanks so much for your help! Once my game sync has finished recharging, I'll check to verify that everything is working correctly again.
