### ISSUE TITLE
Error: Unable to acces jarfile | Macbook M2 Max

### ISSUE THREAD

**Issue by daanotr** [kuroppoi/entralinked#68]
Hi all,

I would like to download the Entralinked emulator. However, when I want to open it, nothing happens and with a command in Terminal I get the error in the picture. Is it possible that this software does not run on mac and only on windows? I have installed all the latest updates of Java and also of Mac OS. Can someone help me with this?

Thanks in advance!
<img width="392" alt="Screenshot 2024-08-07 at 00 12 18" src="https://github.com/user-attachments/assets/cf2eafcd-daa3-447d-92f2-aa9bd179652e">

**Comment by kuroppoi** [comment]
Terminal cannot magically detect where the file is, so you must first navigate to the directory the file is in.
If you've extracted the ZIP file to your desktop you should be able to do something like `cd ~/Desktop/entralinked` 
and then `java -jar entralinked.jar`
