### ISSUE TITLE
ERROR 20100 (I believe) fix

### ISSUE THREAD

**Issue by Alala76** [kuroppoi/entralinked#72]
my problem is, by setting the DNS given by the programm (which I have no issue with running) the connection test fails, thus disconnecting me, I looked it up, and changed the secondary DNS to 1.1.1.1 or 8.8.8.8 (both actually) which solves this problem, but still doesn't allow me to access game sync (20100 error), I read the solution given by the troubleshooting page, but understood none of it, so here I am ! 
Thanks in advance.

**Comment by ev1lbolt** [comment]
https://github.com/kuroppoi/entralinked/wiki/Troubleshooting#052110-x

Had the same issue until I started reading the troubleshooting guide.
To make it quick, it's a permission error, just run start.bat as administrator, it fixed it for me.
After that you'll prolly get error code 60000, just follow the instructions.
