### ISSUE TITLE
This Wi-Fi Connection ID does not exist

### ISSUE THREAD

**Issue by JuliusCM9** [kuroppoi/entralinked#73]
Can someone please help with this.
![IMG_6748](https://github.com/user-attachments/assets/014b00bf-3a77-45f7-abaa-c588bd3273bd)

**Comment by kuroppoi** [comment]
I'm not sure which error code you're getting in-game, but if you're getting the message shown in your screenshot 
then the PID Tool is definitely not the solution for it.
